oakadmin/config/routes.rb
Oakadmin::Application.routes.draw do
  get "top/products"
  get "top/stores"
  get "tickets/index"
  get "tickets/show"
  get "tickets/reply"
  post "sessions/try_login"
  get "sessions/login"
  get "sessions/logout"
  
  root 'dashboard#index'

  get '/product_add_photo/:id', to: 'products#add_photo'
  post '/product_add_photo', to: 'products#add_photo'
  get '/product_delete_photo/:id', to: 'products#delete_photo'

  get '/list_user_tickets', to: 'tickets#list_user_tickets'
  get '/show_user_ticket/:id', to: 'tickets#show_user_ticket'
  post '/show_user_ticket/:id', to: 'tickets#reply_user_ticket'

  get '/list_store_tickets', to: 'tickets#list_store_tickets'
  get '/show_store_ticket/:id', to: 'tickets#show_store_ticket'
  post '/show_store_ticket/:id', to: 'tickets#reply_store_ticket'

  resources :products do
    member do
      get 'features'
    end
  end
  
  resources :admins
  resources :features
  resources :reviews
  resources :users
  resources :stores
  resources :storeusers
  resources :storeproducts
  get '/zipcode/edit/:zid', to: 'zipcodes#edit'
  post '/zipcode/edit/:zid', to: 'zipcodes#update'
  resources :zipcodes
  
end

oakadmin/app/models/zipcode.rb
class Zipcode < ActiveRecord::Base

  self.table_name = 'ZIP_CODES'
  self.primary_key = 'ZIP_CODE'
  self.sequence_name = false

  validates :zip_code, presence: true, length: {minimum: 2, maximum: 10}

end

oakadmin/app/controllers/zipcodes_controller.rb
class ZipcodesController < ApplicationController
  before_action :set_zipcode, only: [:show, :edit, :update, :destroy]

  # GET /zipcodes
  # GET /zipcodes.json
  def index
    @zipcodes = Zipcode.all
  end

  # GET /zipcodes/1
  # GET /zipcodes/1.json
  def show
  end

  # GET /zipcodes/1/edit
  def edit
   

  end

  # PATCH/PUT /zipcodes/1
  # PATCH/PUT /zipcodes/1.json
  def update

      if @zipcode.zip_code != zipcode_params[:zip_code]
        store =  Store.where(:zip_code => @zipcode.zip_code).first
        if store
          flash[:error] = "there is store using this zipcode. Modify it first!"
          redirect_to action: 'index'
          return
        end

        user  = User.where(:zip_code => @zipcode.zip_code).first
        if user
          flash[:error] = "there is user using this zipcode. Modify it first!"
          redirect_to action: 'index'
          return
        end
      end
    respond_to do |format|

      if @zipcode.update(zipcode_params)
        format.html { redirect_to @zipcode, notice: 'Zipcode was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @zipcode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zipcodes/1
  # DELETE /zipcodes/1.json
  def destroy
    @zipcode.destroy
    respond_to do |format|
      format.html { redirect_to zipcodes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zipcode
      puts params[:id]
      @zipcode = Zipcode.where(:zip_code => params[:id]).first
      @zipcode.id = @zipcode.zip_code if @zipcode
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zipcode_params
      params.permit(:zip_code, :city, :country)
    end
end

oakadmin/app/helpers/zipcodes_helper.rb
module ZipcodesHelper
end

oakadmin/app/views/zipcodes/_form.html.haml
= form_for @zipcode do |f|
  - if @zipcode.errors.any?
    #error_explanation
      %h2= "#{pluralize(@zipcode.errors.count, "error")} prohibited this zipcode from being saved:"
      %ul
        - @zipcode.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    %label ZipCode
    %input{:class=>"form-control", :name=>"zip_code", :value=>@zipcode.zip_code}
  .form-group
    %label Country
    %input{:class=>"form-control", :name=>"country", :value=>@zipcode.country}
  .form-group
    %label City
    %input{:class=>"form-control", :name=>"city", :value=>@zipcode.city}
  .actions
    = f.submit 'Save'

oakadmin/app/views/zipcodes/edit.html.haml
%h1 Editing zipcode

= render 'form'

\|
= link_to 'Back', zipcodes_path

oakadmin/app/views/zipcodes/index.html.haml
%h1 
	Listing zipcodes

%table.table.table-striped.datatable
	%thead
		%tr
			%th Zip Code
			%th Country
			%th City
			%th Actions
	%tbody
		- @zipcodes.each do |zipcode|
			%tr
				%td= zipcode.zip_code
				%td= zipcode.country
				%td= zipcode.city
				%td
					%a{:href=>"/zipcodes/#{zipcode.zip_code}/edit", :class=>"btn btn-warning btn-sm"}Edit
					%a{:href=>"/zipcodes/#{zipcode.zip_code}/remove", :class=>"btn btn-sm btn-danger"}Remove

%br

:javascript
	console.log('ready!');
	$('.datatable').dataTable({
	  "sPaginationType": "bootstrap"
	});

oakadmin/app/views/zipcodes/new.html.haml
%h1 New zipcode

= render 'form'

= link_to 'Back', zipcodes_path

oakadmin/app/views/zipcodes/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_zipcode_path(@zipcode)
\|
= link_to 'Back', zipcodes_path