oakadmin/config/routes.rb
Oakadmin::Application.routes.draw do
  get "top/products"
  get "top/stores"
  get "tickets/index"
  get "tickets/show"
  get "tickets/reply"
  post "sessions/try_login"
  get "sessions/login"
  get "sessions/logout"
  
  root 'dashboard#index'

  get '/product_add_photo/:id', to: 'products#add_photo'
  post '/product_add_photo', to: 'products#add_photo'
  get '/product_delete_photo/:id', to: 'products#delete_photo'

  get '/list_user_tickets', to: 'tickets#list_user_tickets'
  get '/show_user_ticket/:id', to: 'tickets#show_user_ticket'
  post '/show_user_ticket/:id', to: 'tickets#reply_user_ticket'

  get '/list_store_tickets', to: 'tickets#list_store_tickets'
  get '/show_store_ticket/:id', to: 'tickets#show_store_ticket'
  post '/show_store_ticket/:id', to: 'tickets#reply_store_ticket'

  resources :products do
    member do
      get 'features'
    end
  end
  
  resources :admins
  resources :features
  resources :reviews
  resources :users
  resources :stores
  resources :storeusers
  resources :storeproducts
  get '/zipcode/edit/:zid', to: 'zipcodes#edit'
  post '/zipcode/edit/:zid', to: 'zipcodes#update'
  resources :zipcodes
  
end

oakadmin/app/models/feature.rb
class Feature < ActiveRecord::Base

    self.table_name = 'FEATURES'
    #self.primary_key = 'PRODUCT_ID'
    self.sequence_name = 'FEATURE_ID_SEQ'

  validates :feature_name, presence: true
  validates :feature_type, presence: true, length: {minimum: 3}

  has_many :productsfeatures
  has_many :products, :through => :productsfeatures

  belongs_to :admin



  before_save :audit_update
  before_create :audit_update
  def audit_update
    self.modified_date = DateTime.now
    if self.created_date.blank?
      self.created_date = DateTime.now
    end
  end

  def type_with_value
    " #{feature_type}: #{feature_name} "
  end
end

oakadmin/app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  before_filter :authenticate_user
  before_action :set_feature, only: [:show, :edit, :update, :destroy]

  # GET /features
  # GET /features.json
  def index
    if params[:query].blank?
      @features = Feature.where('FEATURES.feature_type != ?', "_name")
    else
      p = '%'+params[:query].upcase+'%'
      @features = Feature.where('feature_type LIKE ? OR feature_name LIKE ?' , p, p)
    end
  end

  # GET /features/1
  # GET /features/1.json
  def show
  end

  # GET /features/new
  def new
    @feature = Feature.new
  end

  # GET /features/1/edit
  def edit
  end

  # POST /features
  # POST /features.json
  def create
    @feature = Feature.new(feature_params)
    @feature.created_by = @current_user.admin_id
    @feature.modified_by = @current_user.admin_id
    respond_to do |format|
      if @feature.save
        format.html { redirect_to @feature, notice: 'Feature was successfully created.' }
        format.json { render action: 'show', status: :created, location: @feature }
      else
        format.html { render action: 'new' }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /features/1
  # PATCH/PUT /features/1.json
  def update
    respond_to do |format|
      @feature.modified_by = @current_user.admin_id
      if @feature.update(feature_params)
        format.html { redirect_to @feature, notice: 'Feature was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /features/1
  # DELETE /features/1.json
  def destroy
    @feature.destroy
    respond_to do |format|
      format.html { redirect_to features_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feature
      @feature = Feature.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feature_params
      params.require(:feature).permit(:feature_id, :feature_type, :feature_name)
    end
end

oakadmin/app/helpers/features_helper.rb
module FeaturesHelper
end

oakadmin/app/views/features/_form.html.haml
= form_for @feature do |f|
  - if @feature.errors.any?
    #error_explanation
      %h2= "#{pluralize(@feature.errors.count, "error")} prohibited this feature from being saved:"
      %ul
        - @feature.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :feature_type
    = f.text_field :feature_type, class: "form-control"
  .form-group
    %label Feature name (value)
    = f.text_field :feature_name, class: "form-control"
  .actions
    = f.submit 'Save', {:class=>"btn btn-info"}

oakadmin/app/views/features/edit.html.haml
%h1 Editing feature

= render 'form'

= link_to 'Show', @feature
\|
= link_to 'Back', features_path

oakadmin/app/views/features/index.html.haml
%h1{:class => "page-header"} Listing features
%div{:class => "breadcrumb"}
  = link_to 'New Feature', new_feature_path, {:class=>"btn btn-info"}
%table{:class =>"table table-hover table-striped datatable"}
  %thead
    %tr
      %th #ID
      %th Type
      %th Value
      %th Created by
      %th Created date
      %th Modified by
      %th Modified date
      %th Actions
  %tbody
    - @features.each do |feature|
      %tr
        %td= feature.feature_id
        %td= feature.feature_type
        %td= feature.feature_name
        %td= feature.created_by
        %td= feature.created_date
        %td= feature.modified_by
        %td= feature.modified_date
        %td
          = link_to 'Edit', edit_feature_path(feature), :class => "btn btn-xs btn-warning"
          = button_to 'Destroy', feature, :method => :delete, :class => "btn btn-xs btn-danger", :data => { :confirm => 'Are you sure?' }

%br

%div{:class => "breadcrumb"}
  = link_to 'New Feature', new_feature_path, {:class=>"btn btn-info"}

:javascript
  console.log('ready!');
    $('.datatable').dataTable({
      "sPaginationType": "bootstrap"
    });

oakadmin/app/views/features/new.html.haml
%h1 New feature

= render 'form'

= link_to 'Back', features_path

oakadmin/app/views/features/show.html.haml
%p#notice= notice

%p
  %b Feature:
  = @feature.feature_id
%p
  %b Feature type:
  = @feature.feature_type
%p
  %b Name:
  = @feature.feature_name
%p
  %b Created by:
  = @feature.admin.nick if @feature.admin
%p
  %b Created date:
  = @feature.created_date
%p
  %b Modified by:
  = @feature.admin.nick if @feature.admin
%p
  %b Modified date:
  = @feature.modified_date

= link_to 'Edit', edit_feature_path(@feature)
\|
= link_to 'Back', features_path