oakshopadmin/config/routes.rb
Rails.application.routes.draw do
  get 'offers/index'
  post 'offers/make_offer_save', to: 'offers#make_offer_save'
  get 'offers/show/:id', to: 'offers#show'

  get 'offers/make_offer'

  get '/list_user_tickets', to: 'home#list_user_tickets'
  get '/show_user_ticket/:id', to: 'home#show_user_ticket'
  post '/show_user_ticket/:id', to: 'home#reply_user_ticket'

  get '/list_admin_tickets', to: 'home#list_admin_tickets'
  get '/show_admin_ticket/:id', to: 'home#show_admin_ticket'
  get 'new_admin_ticket', to: 'home#new_admin_ticket'
  post 'new_admin_ticket', to: 'home#new_admin_ticket_save'
  post '/show_admin_ticket/:id', to: 'home#reply_admin_ticket'



	root 'home#index'

	post "sessions/try_login"
	get "sessions/login"
	get "sessions/logout"

	resources :storeusers
	resources :storeproducts
end

oakshopadmin/app/models/storeuser.rb
class Storeuser < ActiveRecord::Base
	attr_accessor :password
	EMAIL_REGEX = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i
	validates :nick, :presence => true, :uniqueness => true, :length => { :in => 4..20 }
	validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
	validates :first_name, :presence => true
	validates :last_name, :presence => true
	validates :password, :confirmation => true , :on=>:create#password_confirmation attr
	validates_length_of :password, :in => 8..20, :on=>:create
	validates :store_id, :presence => true

    self.table_name = 'STORE_USERS'
    #self.primary_key = 'USER_ID'
    self.sequence_name = 'STORE_USER_ID_SEQ'
    before_save :hash_password
	after_save :clear_password

	belongs_to :store

	def hash_password
		puts "hash"
	  if password.present?
	    self.password_salt = BCrypt::Engine.generate_salt
	    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
	  end
	end

	def clear_password
	  #clear in-memory
	  self.password = nil
	end

	def match_password(password_input="")
		password_hash == BCrypt::Engine.hash_secret(password_input, password_salt)
	end

	def self.authenticate(username_or_email="", login_password="")
	  if  EMAIL_REGEX.match(username_or_email)    
	    user = Storeuser.find_by_email(username_or_email)
	  else
	    user = Storeuser.find_by_nick(username_or_email)
	  end
	  if user && user.match_password(login_password)
	    return user
	  else
	    return false
	  end
	end   
	

end

oakshopadmin/app/controllers/storeusers_controller.rb
class StoreusersController < ApplicationController
  before_filter :authenticate_user
  before_action :set_storeuser, only: [:show, :edit, :update, :destroy]

  # GET /storeusers
  # GET /storeusers.json
  def index
    @storeusers = Storeuser.where(:store_id=>@current_user.store_id)
  end

  # GET /storeusers/1
  # GET /storeusers/1.json
  def show
  end

  # GET /storeusers/new
  def new
    @storeuser = Storeuser.new
    @storeuser.store_id = @current_user.store_id
  end

  # GET /storeusers/1/edit
  def edit
  end

  # POST /storeusers
  # POST /storeusers.json
  def create
    @storeuser = Storeuser.new(storeuser_params.except(:password_repeat))
    @storeuser.store_id = @current_user.store_id
    puts @storeuser
    respond_to do |format|
      if @storeuser.save
        flash[:notice] = 'Storeuser was successfully created.'
        format.html { redirect_to action: 'index', notice: 'Storeuser was successfully created.' }
        format.json { render action: 'index', status: :created, location: @storeuser }
      else
        format.html { render action: 'new' }
        format.json { render json: @storeuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /storeusers/1
  # PATCH/PUT /storeusers/1.json
  def update

    respond_to do |format|
      if @storeuser.update(storeuser_params.except(:password_repeat))
        flash[:notice] = "Storeuser was successfully updated."
        format.html { redirect_to action: 'index', notice: 'Storeuser was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @storeuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /storeusers/1
  # DELETE /storeusers/1.json
  def destroy
  	if @storeuser.store_id == @current_user.store_id
	    @storeuser.destroy
	    respond_to do |format|
	      format.html { redirect_to storeusers_url }
	      format.json { head :no_content }
	    end
	end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_storeuser
      @storeuser = Storeuser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def storeuser_params
      params[:storeuser].permit(:nick, :first_name, :last_name, :email, :password, :password_repeat)
    end
end

oakshopadmin/app/helpers/storeusers_helper.rb
module StoreusersHelper
end

oakshopadmin/app/views/storeusers/_form.html.haml
= form_for @storeuser do |f|
  - if @storeuser.errors.any?
    #error_explanation
      %h2= "#{pluralize(@storeuser.errors.count, "error")} prohibited this storeuser from being saved:"
      %ul
        - @storeuser.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :nick
    = f.text_field :nick, class: "form-control"
  .form-group
    = f.label :first_name
    = f.text_field :first_name, class: "form-control"
  .form-group
    = f.label :last_name
    = f.text_field :last_name, class: "form-control"
  .form-group
    = f.label :email
    = f.text_field :email, class: "form-control"
  .form-group
    = f.label :password
    = f.password_field :password, class: "form-control"
  .form-group
    = f.label :repeat_password
    = f.password_field :repeat_password, class: "form-control"

  .actions
    = f.submit 'Save'

oakshopadmin/app/views/storeusers/edit.html.haml
= render 'form'

oakshopadmin/app/views/storeusers/index.html.haml
%h1 
  Listing users
  %a.btn.btn-success{:href=>"storeusers/new"}
    Add user
%table.table.table-striped.datatable#hiho
  %thead
    %tr
      %th ID
      %th Nick
      %th First Name
      %th Last Name
      %th Email
      %th Actions
  %tbody    
    - @storeusers.each do |user|
      %tr
        %td= user.store_user_id
        %td= user.nick
        %td= user.first_name
        %td= user.last_name
        %td= user.email
        %td
          = link_to 'Show', user,  :class => "btn btn-xs btn-info"
          = link_to 'Edit', edit_storeuser_path(user),  :class => "btn btn-xs btn-warning"
          = button_to 'Remove', user, :method => :delete, :class => "btn btn-xs btn-danger", :data => { :confirm => 'Are you sure?' }

%br

:javascript
  console.log('ready!');
    $('.datatable').dataTable({
      "sPaginationType": "bootstrap"
    });

oakshopadmin/app/views/storeusers/new.html.haml
%h1 New storeuser

= form_for @storeuser do |f|
  - if @storeuser.errors.any?
    #error_explanation
      %h2= "#{pluralize(@storeuser.errors.count, "error")} prohibited this storeuser from being saved:"
      %ul
        - @storeuser.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :nick
    = f.text_field :nick, class: "form-control"
  .form-group
    = f.label :first_name
    = f.text_field :first_name, class: "form-control"
  .form-group
    = f.label :last_name
    = f.text_field :last_name, class: "form-control"
  .form-group
    = f.label :email
    = f.text_field :email, class: "form-control"
  .form-group
    = f.label :password
    = f.password_field :password, class: "form-control"
  .form-group
    = f.label :password_confirmation
    = f.password_field :password_confirmation, class: "form-control"

  .actions
    = f.submit 'Save'


= link_to 'Back', storeusers_path